<?php include('header.php');?>

<div id="container-div">
	<div class="para-text">

   <div> <h1 id="about">ABOUT</h1></div>
		<p style="font-size:13px;"><?php echo"
		This(International Business Machines Corporation) is an American multinational technology company headquartered in Armonk, New York, 
		United States, with operations in over 170 countries. The company originated in 1911 as the Computing-Tabulating-Recording Company 
		(CTR) and 
		was renamed in 1924.

		company manufactures and markets computer hardware, middleware and software, and offers hosting and consulting services in areas
		ranging from 
		mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most patents generated by
		a business 
		(as of 2017) for 24 consecutive years.[5] Inventions by company include the automated teller machine (ATM), the PC, the floppy disk, 
		the hard disk 
		drive, 
		the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory 
		(DRAM). 
		The company mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.

		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go , continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.
		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go , continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.
		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go, continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.
		The company mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.

		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go, continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.
		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go, continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.
		company has continually shifted its business mix by commoditizing markets focusing on higher-value, more profitable markets. 
		This includes spinning off printer manufacturer Lexmark in 1991 and selling off its personal computer (ThinkPad/ThinkCentre) and 
		x86-based 
		server businesses to Lenovo (2005 and 2014, respectively), and acquiring companies such as PwC Consulting (2002), SPSS (2009), and 
		The Weather Company (2016). Also in 2014, IBM announced that it would go , continuing to design semiconductors, 
		but offloading manufacturing to GlobalFoundries.</p></br>";?>
	
<?php include('footer.php');?> 
</body>

</html>